### ISSUE TITLE
Put user analytics system in place

### ISSUE THREAD

**Issue by siwhitehouse** [openownership/data-standard-sphinx-theme#55]
We're not currently using Google Analytics to track readership of the documentation ([ReadTheDocs admin](https://readthedocs.org/dashboard/beneficial-ownership-data-standard/advanced/))

And currently there's [no in-built RTD analytics](https://docs.readthedocs.io/en/stable/commercial/analytics.html?highlight=analytics)

If there is no other mechnism, then we should get something in place.

**Comment by siwhitehouse** [comment]
Copied from the (internal) Open Data Services issue at http://bods.opendataservices.coop/redmine/issues/510

**Comment by stevenday** [comment]
I believe this ticket is slightly out of date now that we use Matamo, however, we'd like to change this to Google Analytics so that all our usage analytics are available in one place. I can generate and provide the relevant GA code, but I presume we'll also need to update the privacy/cookies policy to refer to this.

**Comment by siwhitehouse** [comment]
@stevenday Yes, I failed to update the issue when I copied it across. We [tell users that we use Matomo](http://standard.openownership.org/en/v0-2-0/about/privacy-notice.html#understanding-website-visitor-and-traffic-patterns) and we include that advice in Russian translation as well. 

We do not currently have an agreed mechanism for making ad hoc updates to the website in between schema versions. 

I've created a new issue for this at https://github.com/openownership/data-standard/issues/279

**Comment by Lathrisk** [comment]
It doesn't look like the piwik snippet is tracking anything too complex so imagine this will be a like-for-like replacement with Google Analytics.

@stevenday have you set up a Google Analytics account? I think they provide a snippet to insert that contains the GA code. Could you send that over, or provide access to the GA account?

(Also, I can set up a branch with the relevant changes into which the copy can be added once translation is resolved. If that matches the expected workflow.)

**Comment by stevenday** [comment]
@Lathrisk - I just created one, here's the snippet:

```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-158633237-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-158633237-1');
</script>
```

If the current code is doing anything fancy to track other resources (PDF downloads for example), we should probably use our Google Tag Manager setup instead (we have this on the main site since a lot of the resources are downloadable). Just let me know and I can set that up.

I think a new branch + PR which we can then resolve the translation issue on is ideal, thanks.
